# vs code/market place/ rest client  

GET http://localhost:3000/posts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc3VkIiwidXNlckFnZSI6MjgsImlhdCI6MTY2NDQ4NjU2OSwiZXhwIjoxNjY0NDg2NTk5fQ.5gFeSvt964ga5qM0zXPjzPO_NTP9EHiSx7i1h8m72FE


###
POST  http://localhost:4000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc3VkIiwidXNlckFnZSI6MjgsImlhdCI6MTY2NDQ4NjUyNH0.pksdnM7QHexWE_nfLUGQPuFAKNF1D2ebys4tR_YbOjw"
}

###
DELETE   http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc3VkIiwidXNlckFnZSI6MjgsImlhdCI6MTY2NDQ4NjUyNH0.pksdnM7QHexWE_nfLUGQPuFAKNF1D2ebys4tR_YbOjw"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Masud",
    "userAge":28
}